#+STARTUP: content logdone
#+AUTHOR: Isak Falk
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t
#+EXCLUDE_TAGS: :noexport:

* Pages
:PROPERTIES:
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
:EXPORT_HUGO_MENU: :menu main
:EXPORT_HUGO_SECTION: pages
:EXPORT_HUGO_WEIGHT: auto
:END:

** Page Title
:PROPERTIES:
:EXPORT_FILE_NAME: page-title
:END:

Page content

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: blog
:END:

** TODO Version controlling dotfiles and backup of computer   :productivity:
:PROPERTIES:
:EXPORT_FILE_NAME: version-control-dotfiles-and-computer-backup
:END:

** TODO Sounding smart, being dumb                       :academics:writing:
:PROPERTIES:
:EXPORT_FILE_NAME: sounding-smart-being-dumb
:END:

Blog post about how obfuscating writing by using flowery and waffly language to
indirectly confuse readers is a bad approach and hurts trying to convey
information to your audience.

*** Outline
Working outline something like this

**** Context
/Less is more/. That's a fitting way to describe the relationship between a text and
its quality. I have a pretty good grip of the English language having lived in
the UK for more than 5 years, but one thing I am not particularly happy about is
how my default way of writing obfuscates rather than clarifies.

I did a maths degree for my undergraduate and it was probably one of the best
options in terms of the skills I learned and how it changed the way I think. The
main downside of this is that /it did not prepare me how to write in a clear way
outside of mathematical and logical arguments/.

This has influenced my writing in a way that I don't think is good for
explaining concepts in a clear way to others, while also making it seem more
plausible due to use of mathematical and scientific terms. This together with
the fact that I don't have experience in writing (blogging or otherwise) makes
my style dense and hard to grasp possibly mirroring how texts filled with dense
terminology and equations get the benefit of doubt, for free [cite source].

**** A mathematical proof
A mathematical proof is a form of logical
argument, where you put forward your assumptions and then show how these
assumptions leads to a conclusion. I don't want to talk about what these forms
of arguments are, but /how they are constructed/ and /the language use when
writing them/.

Since a proof is a human way of writing the equivalent of logical notation, it
uses words seldomly used in everyday life, often with an archaic flavour to
them. A couple of these are words such as
- Hence
- Thus
- Therefore
and phrases including
- We see that
- Due to this
- Consider the following

**** Solution

** Topic                                                             :@topic:
*** DONE Post Title                                             :post:tags:
CLOSED: [2017-12-19 Tue 17:00]
:PROPERTIES:
:EXPORT_DATE: 2017-12-19
:EXPORT_FILE_NAME: post-title-in-slug-form
:END:

Content

More content

#+BEGIN_SRC bash -l 7 :hl_lines 8
  echo 'Some source code content'
  echo 'This line will be highlighted'
  echo "This one won't"
#+END_SRC

**** Post Sub-Heading
This is another section within the post.

*** TODO Draft Post Title
:PROPERTIES:
:EXPORT_FILE_NAME: draft-post-title
:END:

This article *will* be exported but will be marked ~draft = true~ in the front matter.

* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (add-hook 'after-save-hook #'org-hugo-export-wim-to-md-after-save :append :local)
# eval: (auto-fill-mode 1)
# End:
